kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: wdm4containerregistry.azurecr.io/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: silo
spec:
  selector:
    matchLabels:
      app: silo
  serviceName: silo
  replicas: 3
  template:
    metadata:
      labels:
        app: silo
    spec:
      containers:
      - name: silo
        image: wdm4containerregistry.azurecr.io/silo:latest
        imagePullPolicy: Always
        env:
        - name: ClusterId
          value: AKSCluster
        ports:
        - name: orleansgateway
          containerPort: 30000
        - name: orleansport
          containerPort: 11111
