kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: wdm4containerregistry.azurecr.io/api:latest
        args: ["url=http://0.0.0.0:80", "silohost=silo" ]
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: wdm4secret
---
kind: Service
apiVersion: v1
metadata:
  name: silo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: silo
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 30000
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: silo
spec:
  selector:
    matchLabels:
      app: silo
  serviceName: silo
  replicas: 3
  template:
    metadata:
      labels:
        app: silo
    spec:
      containers:
      - name: silo
        image: wdm4containerregistry.azurecr.io/silo:latest
        env:
        - name: ClusterId
          value: AKSCluster
        ports:
        - name: orleansgateway
          containerPort: 30000
        - name: orleansport
          containerPort: 11111
        volumeMounts:
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
        imagePullSecrets:
        - name: wdm4secret
      volumes:
      - name: secrets
        secret:
          secretName: orleanssecret

