version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY}api
    build:
      context: .
      dockerfile: src/Cart.API/Dockerfile
    ports:
      - 80:80
    links:
      - silo

  silo:
    image: ${DOCKER_REGISTRY}silo
    build:
      context: .
      dockerfile: src/Silo/Dockerfile

