version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY}api
    build:
      context: .
      dockerfile: src/Cart.API/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - silo
    networks:
      - my-net
  silo:
    image: ${DOCKER_REGISTRY}silo
    build:
      context: .
      dockerfile: src/Silo/Dockerfile
    networks:
      - my-net
networks:
  my-net:
    driver: bridge
    attachable: true