version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/Cart.API/Dockerfile
    ports:
      - 80:80
    depends_on:
      - silo
  silo:
    image: silo
    build:
      context: .
      dockerfile: src/Silo/Dockerfile
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=P@55w0rd
      - MYSQL_DATABASE=cart
