version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/Cart.API/Dockerfile
    ports:
      - 3000:80
    links:
      - silo

  silo:
    image: silo
    build:
      context: .
      dockerfile: src/Silo/Dockerfile

